const produkData = [
        {sku: "CBP-24", nama: "GILLETTE BLUE 2 PLUS 1 HANGER", hpp: 44000, unitPacking: 1},
        {sku: "CBP-6", nama: "GILLETTE BLUE 2 PLUS 6 PCS", hpp: 11000, unitPacking: 1},
        {sku: "CBP-12", nama: "GILLETTE BLUE 2 PLUS 1/2 HANGER", hpp: 22000, unitPacking: 1},
        {sku: "CBP-96", nama: "GILLETTE BLUE 2 PLUS 4 HANGER", hpp: 176000, unitPacking: 4},
        {sku: "CGK-72", nama: "GILLETTE GOAL 2 RAZOR 3 HANGER", hpp: 119000, unitPacking: 3},
        {sku: "CGK-24", nama: "GILLETTE GOAL 2 RAZOR 1 HANGER", hpp: 40000, unitPacking: 1},
        {sku: "CGK-12", nama: "GILLETTE GOAL 2 RAZOR 1/2 HANGER", hpp: 20000, unitPacking: 1},
        {sku: "CGK-6", nama: "GILLETTE GOAL 2 RAZOR 6PCS", hpp: 10000, unitPacking: 1},
        {sku: "CF-24", nama: "GILLETTE BLUE 2 FLEXI 1 HANGER", hpp: 66000, unitPacking: 1},
        {sku: "CF-12", nama: "GILLETTE BLUE 2 FLEXI 1/2 HANGER", hpp: 33000, unitPacking: 1},
        {sku: "CF-E01", nama: "GILLETTE BLUE 2 FLEXI ECER 1 PCS", hpp: 3000, unitPacking: 1},
        {sku: "GK2", nama: "GILLETTE GOAL KLIK 2 HANGER", hpp: 40000, unitPacking: 2},
        {sku: "GK", nama: "GILLETTE GOAL KLIK 1 HANGER", hpp: 20000, unitPacking: 1},
        {sku: "GK-E01", nama: "GILLETTE GOAL KLIK ECER 1 PCS", hpp: 3500, unitPacking: 1},
        {sku: "GP-5P", nama: "Silet Gillette Goal Platinum 5 1 HANGER", hpp: 44000, unitPacking: 1},
        {sku: "GP-52P", nama: "Silet Gillette Goal Platinum 5 1/2 HANGER", hpp: 22000, unitPacking: 1},
        {sku: "GP-51P", nama: "Silet Gillette Goal Platinum 5+1", hpp: 48500, unitPacking: 1},
        {sku: "GP-512P", nama: "Silet Gillette Goal Platinum 5+1 1/2 HANGER", hpp: 24500, unitPacking: 1},
        {sku: "LB", nama: "GILLETTE LONDON BRIDGE 1 HANGER", hpp: 71500, unitPacking: 1},
        {sku: "LB10", nama: "GILLETTE LONDON BRIDGE 1/2 HANGER", hpp: 36000, unitPacking: 1},
        {sku: "MT-FF", nama: "MINYAK TAWON FF", hpp: 12500, unitPacking: 1},
        {sku: "MT-EE", nama: "MINYAK TAWON EE", hpp: 12500, unitPacking: 1},
        {sku: "MT-DD", nama: "MINYAK TAWON DD", hpp: 6500, unitPacking: 1},
        {sku: "MT-CC", nama: "MINYAK TAWON CC", hpp: 6500, unitPacking: 1},
        {sku: "MTFF-1BOX", nama: "MINYAK TAWON FF 1 BOX", hpp: 148500, unitPacking: 1},
        {sku: "MTDD-1BOX", nama: "MINYAK TAWON DD 1 BOX", hpp: 151500, unitPacking: 1},
        {sku: "MTCC-1BOX", nama: "MINYAK TAWON CC 1 BOX", hpp: 150000, unitPacking: 1},
        {sku: "KBRS-Y1P", nama: "KAMPER YUKINAWA 1 PACK", hpp: 29000, unitPacking: 1},
        {sku: "KBRS-Y12PC", nama: "KAMPER YUKINAWA 12 PCS", hpp: 14500, unitPacking: 1},
        {sku: "KBRS-YE01", nama: "KAMPER YUKINAWA 1 PCS", hpp: 1500, unitPacking: 1},
        {sku: "KBRS-SG1P", nama: "KAMPER SEAGUL 1 PACK", hpp: 29000, unitPacking: 1},
        {sku: "KBRS-SG12PC", nama: "KAMPER SEAGUL 12 PCS", hpp: 14500, unitPacking: 1},
        {sku: "KBRS-SGE01", nama: "KAMPER SEAGUL 1 PCS", hpp: 1500, unitPacking: 1},
        {sku: "PVC-ISR1P", nama: "ISARPLAS 1 PACK", hpp: 58500, unitPacking: 1},
        {sku: "PVC-ISR01E", nama: "ISARPLAS 1 PCS", hpp: 5500, unitPacking: 1},
        {sku: "OP1", nama: "OKE PLAST 1 PACK", hpp: 22000, unitPacking: 1},
        {sku: "HP1", nama: "HANSAPLAST 1 PACK", hpp: 28500, unitPacking: 1},
        {sku: "CTR-K150P", nama: "KENKO L150 1 PACK", hpp: 38500, unitPacking: 1},
        {sku: "CTR-K150E", nama: "KEKNO L150 1 PCS", hpp: 3500, unitPacking: 1},
        {sku: "KL500-1B", nama: "KENKO L500", hpp: 110000, unitPacking: 1},
        {sku: "CB-YD1P", nama: "CB YUKINAWA DEWASA 100 1 PACK", hpp: 15000, unitPacking: 1},
        {sku: "STN", nama: "SOLASI TAPE NATIONAL", hpp: 5500, unitPacking: 1},
        {sku: "KG", nama: "KOREK GAS G2000", hpp: 43000, unitPacking: 1},
        {sku: "KG-YUKI", nama: "KOREK GAS YUKITO", hpp: 43000, unitPacking: 1},
        {sku: "BP", nama: "STANDARD C88 CASTELLO 1 PACK", hpp: 14500, unitPacking: 1},
        {sku: "BP-H", nama: "PILOT BPTP 1 PACK", hpp: 12000, unitPacking: 1},
        {sku: "BPLT-1BOX", nama: "PILOT BPTP 1 BOX 12 PACK", hpp: 143000, unitPacking: 1},
        {sku: "SGF", nama: "SIKAT GIGI FORMULA", hpp: 35500, unitPacking: 1},
        {sku: "KB-B", nama: "KAPUR SEMUT BAGUS 1B", hpp: 5500, unitPacking: 1},
        {sku: "KB-S", nama: "KAPUR SEMUT BAGUS 1S", hpp: 33000, unitPacking: 1},
        {sku: "JH-PW12", nama: "JAS HUJAN PONCHO WARNA 12PCS", hpp: 46500, unitPacking: 1},
        {sku: "JH-PW6", nama: "JAS HUJAN PONCHO WARNA 6PCS", hpp: 23500, unitPacking: 1},
        {sku: "JH-JC6", nama: "JAS HUJAN JAKET CELANA 6PCS", hpp: 22000, unitPacking: 1},
        {sku: "JH-JC12", nama: "JAS HUJAN JAKET CELANA 12PCS", hpp: 44000, unitPacking: 1},
        {sku: "JH-P6", nama: "JAS HUJAN PONCHO HDPE 6PCS", hpp: 19500, unitPacking: 1},
        {sku: "JH-P12", nama: "JAS HUJAN PONCHO HDPE 12PCS", hpp: 39000, unitPacking: 1},
        {sku: "JH-PPE6", nama: "JAS HUJAN PONCHO PE 6PCS", hpp: 14500, unitPacking: 1},
        {sku: "JH-PPE12", nama: "JAS HUJAN PONCHO PE 12PCS", hpp: 29000, unitPacking: 1},
        {sku: "TP-K", nama: "PATRI CAIR 1 PCS", hpp: 1000, unitPacking: 1},
        {sku: "TP", nama: "PATRI CAIR 1 PCS", hpp: 1000, unitPacking: 1},
        {sku: "TP-K10", nama: "PATRI CAIR 10 PCS", hpp: 9500, unitPacking: 1},
        {sku: "TPT", nama: "Tambal Panci Tempel 1 Renceng isi 10 PcS", hpp: 1000, unitPacking: 1},
        {sku: "KJA1L", nama: "SERBET KJA", hpp: 36500, unitPacking: 1},
        {sku: "AM-100", nama: "AMPLOP 100", hpp: 6000, unitPacking: 1},
        {sku: "KOKM", nama: "KOK MATARAM", hpp: 27500, unitPacking: 1},
        {sku: "GKW-1R", nama: "GUNTING ORLEE 1 RENTENG", hpp: 22000, unitPacking: 1},
        {sku: "GKW", nama: "GUNTING ORLEE 1 PCS", hpp: 1500, unitPacking: 1},
        {sku: "SCP-L", nama: "SABUT CUCI PIRING LIDA", hpp: 7500, unitPacking: 1},
        {sku: "JS1KD", nama: "JARUM SOL SEPATU 1 KODI", hpp: 22000, unitPacking: 1},
        {sku: "TK", nama: "Tas Karung Serbaguna Ukuran sedang | Tas belanja Sayur buah", hpp: 2000, unitPacking: 1},
        {sku: "SKM-01E", nama: "SIKAT KIMO ECER", hpp: 2500, unitPacking: 1},
        {sku: "KG-1", nama: "KARUNG GONI", hpp: 36500, unitPacking: 1},
        {sku: "KT-GA", nama: "KERTAS TELO GRADE A", hpp: 8000, unitPacking: 1},
        {sku: "KT-GA+", nama: "KERTAS TELO GRADE A++", hpp: 8000, unitPacking: 1},
        {sku: "KJM2", nama: "KOREK JUMBO M2000", hpp: 7500, unitPacking: 1},
        {sku: "KAT-1B", nama: "KOREK TOKAI", hpp: 87000, unitPacking: 1},
        {sku: "KWC", nama: "KAMPER WC WARNA", hpp: 0, unitPacking: 1},
        {sku: "BPS-1S", nama: "BALL PING-PONG SHIELD", hpp: 8000, unitPacking: 1},
        {sku: "RTC-MW", nama: "RACUN TIKUS CAIR MAOWANG", hpp: 8500, unitPacking: 1},
        {sku: "RT-PM", nama: "RACUN TIKUS PACMAN", hpp: 16500, unitPacking: 1},
        {sku: "SW-KJA", nama: "SERBET WARNA KJA", hpp: 35500, unitPacking: 1},
        {sku: "RT-BH", nama: "RACUN TIKUS BAEGUN HIJAU", hpp: 16500, unitPacking: 1},
        {sku: "RT-TX", nama: "RACUN TIKUS TEMIX MERAH", hpp: 16500, unitPacking: 1},
        {sku: "TB-TR", nama: "TALI BAGASI TALI ROT", hpp: 3500, unitPacking: 1},
        {sku: "SP-SPR6", nama: "SPIRTUS SPRAY 6PCS", hpp: 15000, unitPacking: 1},
        {sku: "SP-SPR12", nama: "SPIRTUS SPRAY 12PCS", hpp: 30000, unitPacking: 1},
        {sku: "SP-B500", nama: "SPIRTUS BOTOL 500ML", hpp: 8000, unitPacking: 1},
        {sku: "DT-24M12P", nama: "DOUBLE TAPE 24MM 1 SLOP", hpp: 19000, unitPacking: 1},
        {sku: "DT-24M06P", nama: "DOUBLE TAPE 24MM 1/2 SLOP", hpp: 9500, unitPacking: 1},
        {sku: "DT-12M24P", nama: "DOUBLE TAPE 12MM 1 SLOP", hpp: 19000, unitPacking: 1},
        {sku: "DT-12M12P", nama: "DOUBLE TAPE 12MM 1/2 SLOP", hpp: 9500, unitPacking: 1},
        {sku: "KBS", nama: "KARUNG BAGOR SERBAGUNA BERSIH", hpp: 2500, unitPacking: 1},
        {sku: "KPL-100", nama: "KOREK PELANGI 100PCS", hpp: 30500, unitPacking: 1},
        {sku: "KPL-50", nama: "KOREK PELANGI 50PCS", hpp: 15500, unitPacking: 1},
        {sku: "KPL-20", nama: "KOREK PELANGI 20PCS", hpp: 6500, unitPacking: 1},
        {sku: "KKC-100", nama: "KOREK KUCING 100 PCS", hpp: 37000, unitPacking: 1},
        {sku: "KKC-50", nama: "KOREK KUCING 50 PCS", hpp: 18500, unitPacking: 1},
        {sku: "KKC-20", nama: "KOREK KUCING 20 PCS", hpp: 7500, unitPacking: 1},
        {sku: "L-PGD100", nama: "LEM LALAT PAGODA 1 BOX", hpp: 40000, unitPacking: 1},
        {sku: "L-PGD50", nama: "LEM LALAT PAGODA 5 PACK", hpp: 20000, unitPacking: 5},
        {sku: "L-PGD30", nama: "LEM LALAT PAGODA 3 PACK", hpp: 12000, unitPacking: 3},
        {sku: "L-PGD20", nama: "LEM LALAT PAGODA 2 PACK", hpp: 8000, unitPacking: 2},
        {sku: "L-PGD10", nama: "LEM LALAT PAGODA 1 PACK", hpp: 4000, unitPacking: 1},
        {sku: "ABCB-4PCS", nama: "ABC A2 BIRU 4 PCS ", hpp: 10000, unitPacking: 1},
        {sku: "ABCB-1BOX", nama: "ABC A2 BIRU 1 BOX", hpp: 58500, unitPacking: 1},
        {sku: "ABCH-4PCS", nama: "ABC A2 HUJAU 4 PCS", hpp: 8500, unitPacking: 1},
        {sku: "ABCH-1BOX", nama: "ABC A2 HIJAU 1 BOX", hpp: 49500, unitPacking: 1},
        {sku: "ABCA3-6PCS", nama: "ABC A3 6 PCS", hpp: 10000, unitPacking: 1},
        {sku: "ABCA3-12PCS", nama: "ABC A3 12 PCS", hpp: 19500, unitPacking: 1},
        {sku: "RFW-1BOX", nama: "REMI FW 1 BOX", hpp: 41500, unitPacking: 1},
        {sku: "RFW-1PACK", nama: "REMI FW 1 PACK", hpp: 4000, unitPacking: 1},
        {sku: "RGL-1BOX", nama: "REMI GOODLAKE 1 BOX", hpp: 36500, unitPacking: 1},
        {sku: "RGL-1PCS", nama: "REMI GOODLAKE 1 PCS", hpp: 3500, unitPacking: 1},
        {sku: "RB-1BOX", nama: "REMI BATIK 1 BOX", hpp: 42000, unitPacking: 1},
        {sku: "RB-1PCS", nama: "REMI BATIK 1 PCS", hpp: 4000, unitPacking: 1},
        {sku: "PGLUV-1BOX", nama: "GLUVINAL PACKMAN 1 BOX", hpp: 46500, unitPacking: 1},
        {sku: "PGLUV-1PCS", nama: "GLUVINAL PACKMAN 1 PCS", hpp: 2000, unitPacking: 1},
        {sku: "LGK-1PCS", nama: "LEM G KOREA 1PCS", hpp: 3000, unitPacking: 1},
        {sku: "LGK-1BOX", nama: "LEM G KOREA 1BOX", hpp: 148500, unitPacking: 1},
        {sku: "PFC-1BOX", nama: "PENSIL 2B FABER CASTEL 1 BOX 6 PACK", hpp: 60500, unitPacking: 1},
        {sku: "PFC-1PACK", nama: "PENSIL 2B FABER CASTEL 1 PACK", hpp: 10500, unitPacking: 1},
        {sku: "SK25-1SLOP", nama: "SOLASI KADO 25YARD 1 SLOP", hpp: 11000, unitPacking: 1},
        {sku: "HN-MRH", nama: "HENNA MERAH", hpp: 9000, unitPacking: 1},
        {sku: "HN-CKLT", nama: "HENNA COKLAT", hpp: 9000, unitPacking: 1},
        {sku: "HN-ORG", nama: "HENNA ORANGE", hpp: 9000, unitPacking: 1},
        {sku: "HN-PINK", nama: "HENNA PINK", hpp: 9000, unitPacking: 1},
        {sku: "HN-HTM", nama: "HENNA HITAM", hpp: 9000, unitPacking: 1},
        {sku: "HN-MRN", nama: "HENNA MAROON", hpp: 9000, unitPacking: 1},
        {sku: "HL-MRH", nama: "HALAL MERAH", hpp: 9000, unitPacking: 1},
        {sku: "HL-BRWN", nama: "HALAL COKLAT", hpp: 9000, unitPacking: 1},
        {sku: "HL-ORG", nama: "HALAL ORANGE", hpp: 9000, unitPacking: 1},
        {sku: "HL-PINK", nama: "HALAL PINK", hpp: 9000, unitPacking: 1},
        {sku: "HL-BLCK", nama: "HALAL HITAM", hpp: 9000, unitPacking: 1},
        {sku: "HL-MRN", nama: "HALAL MAROON", hpp: 9000, unitPacking: 1},
        {sku: "INM-MRH", nama: "INAI MUSLIMAH MERAH", hpp: 9000, unitPacking: 1},
        {sku: "INM-CKLT", nama: "INAI MUSLIMAH COKLAT", hpp: 9000, unitPacking: 1},
        {sku: "INM-ORG", nama: "INAI MUSLIMAH ORANGE", hpp: 9000, unitPacking: 1},
        {sku: "INM-PINK", nama: "INAI MUSLIMAH PINK", hpp: 9000, unitPacking: 1},
        {sku: "INM-HTM", nama: "INAI MUSLIMAH HITAM", hpp: 9000, unitPacking: 1},
        {sku: "INM-MRN", nama: "INAI MUSLIMAH MAROON", hpp: 9000, unitPacking: 1},
        {sku: "INAI-MRH", nama: "INAI MERAH", hpp: 9000, unitPacking: 1},
        {sku: "INAI-CKLT", nama: "INAI COKLAT", hpp: 9000, unitPacking: 1},
        {sku: "INAI-ORG", nama: "INAI ORANGE", hpp: 9000, unitPacking: 1},
        {sku: "INAI-PNK", nama: "INAI PINK", hpp: 9000, unitPacking: 1},
        {sku: "INAI-HTM", nama: "INAI HITAM", hpp: 9000, unitPacking: 1},
        {sku: "INAI-MRN", nama: "INAI MAROON", hpp: 9000, unitPacking: 1},
        {sku: "PTL-K1", nama: "PENTIL SEPEDA KUNING 1 IKAT", hpp: 5000, unitPacking: 1},
        {sku: "PTL-K10", nama: "PENTIL SEPEDA KUNING 10 IKAT (1 PACK)", hpp: 45500, unitPacking: 1},
        {sku: "PTL-M1", nama: "PENTIL SEPEDA MERAH 1 IKAT", hpp: 5000, unitPacking: 1},
        {sku: "PTL-M10", nama: "PENTIL SEPEDA MERAH 10 IKAT (1 PACK)", hpp: 45500, unitPacking: 1},
        {sku: "MTN-20", nama: "SILET MONTANA 1  HANGER", hpp: 44000, unitPacking: 1},
        {sku: "MTN-10", nama: "SILET MONTANA 1/2 HANGER", hpp: 22000, unitPacking: 1},
        {sku: "DRC-20", nama: "SILET DORCO 1 HANGER", hpp: 79500, unitPacking: 1},
        {sku: "DRC-10", nama: "SILET DORCO 1/2 HANGER", hpp: 40000, unitPacking: 1},
        {sku: "SLTZRCH-20", nama: "SILET ZURICH 1 HANGER", hpp: 43000, unitPacking: 1},
        {sku: "SLTZRCH-10", nama: "SILET ZURICH 1/2 HANGER", hpp: 21500, unitPacking: 1},
        {sku: "KREXIA-1BOX", nama: "KOREK EXIA", hpp: 51000, unitPacking: 1},
        {sku: "ZBJMB-1BOX", nama: "ZAKU BARA JUMBO 1 BOX", hpp: 275000, unitPacking: 1},
        {sku: "ZBJMB-1PCS", nama: "ZAKU BARA JUMBO 1 PCS", hpp: 11000, unitPacking: 1},
        {sku: "ZBBTK-1BOX", nama: "ZAKU BARA BATIK 1 BOX", hpp: 275000, unitPacking: 1},
        {sku: "ZBBTK-1PCS", nama: "ZAKU BARA BATIK 1 PCS", hpp: 11000, unitPacking: 1},
        {sku: "ZBKCL-1BOX", nama: "ZAKU BARA KECIL 1 BOX", hpp: 121000, unitPacking: 1},
        {sku: "ZBKCL-1PCS", nama: "ZAKU BARA KECIL 1 PCS", hpp: 5000, unitPacking: 1},
        {sku: "FBKCL-1BOX", nama: "FORTIS BARA KECIL 1 BOX", hpp: 124000, unitPacking: 1},
        {sku: "FBKCL-1PCS", nama: "FORTIS BARA KECIL 1 PCS", hpp: 5000, unitPacking: 1},
        {sku: "BHTM-1R", nama: "BENANG JAHIT HITAM", hpp: 14500, unitPacking: 1},
        {sku: "BPTH-1R", nama: "BENANG JAHIT PUTIH", hpp: 14500, unitPacking: 1},
        {sku: "BWRN-1R", nama: "BENANG JAHIT WARNA", hpp: 13500, unitPacking: 1},
        {sku: "GBSR-1PCS", nama: "GUNTING M2000 BESAR 1PCS", hpp: 6500, unitPacking: 1},
        {sku: "GBSR-1BOX", nama: "GUNTING M2000 BESAR 1 BOX", hpp: 71500, unitPacking: 1},
        {sku: "GSDNG-1PCS", nama: "GUNTING M2000 SEDANG 1PCS", hpp: 4500, unitPacking: 1},
        {sku: "GSDNG-1BOX", nama: "GUNTING M2000 SEDANG 1 BOX", hpp: 48500, unitPacking: 1},
        {sku: "GKCL-1PCS", nama: "GUNTING M2000 KECIL 1PCS", hpp: 3500, unitPacking: 1},
        {sku: "GKCL-1BOX", nama: "GUNTING M2000 KECIL 1 BOX", hpp: 36500, unitPacking: 1},
        {sku: "PLPNPRT-1BOX", nama: "PARETTO BALLPOINT 1 BOX 12 PACK", hpp: 88000, unitPacking: 1},
        {sku: "PLPNPRT-1PACK", nama: "PARETTO BALLPOINT 1 PACK", hpp: 7500, unitPacking: 1},
        {sku: "RTO-1BOX", nama: "KARTU REMI TOP ONE 1 BOX 12 PACK", hpp: 31000, unitPacking: 1},
        {sku: "RTO-1PACK", nama: "KARTU REMI TOP ONE 1 PACK", hpp: 3000, unitPacking: 1},
        {sku: "ALMTAPE-5M", nama: "ALUMUNIUM TAPE 5M 1PCS", hpp: 6500, unitPacking: 1},
        {sku: "ALMTAPE5M-1KRT", nama: "ALUMUNIUM TAPE 5M 1 KARTON", hpp: 423500, unitPacking: 1},
        {sku: "ALMTAPE-10M", nama: "ALUMUNIUM TAPE 10M 1PCS", hpp: 9500, unitPacking: 1},
        {sku: "ALMTAPE10M-1KRT", nama: "ALUMUNIUM TAPE 10M 1 KARTON", hpp: 652000, unitPacking: 1},
        {sku: "LTC-1PCS", nama: "LEM TIKUS COBRA 1PCS", hpp: 5500, unitPacking: 1},
        {sku: "LTC-1PACK", nama: "LEM TIKUS COBRA 1PACK 12PCS", hpp: 60500, unitPacking: 1},
        {sku: "BVOLI-1PCS", nama: "BOLA VOLLY 1PCS", hpp: 6500, unitPacking: 1},
        {sku: "BVOLI-1PACK", nama: "BOLA VOLLY 1 PACK 6PCS", hpp: 36500, unitPacking: 1},
        {sku: "PNT-1BOX", nama: "PENITI SWAN 1 BOX", hpp: 35500, unitPacking: 1},
        {sku: "PNT-1/2BOX", nama: "PENITI SWAN 1/2 BOX", hpp: 18000, unitPacking: 1},
        {sku: "LPCMN-1BOX", nama: "LEM KERTAS PACMAN 1 BOX", hpp: 33000, unitPacking: 1},
        {sku: "LPCMN-1PCS", nama: "LEM KERTAS PACMAN 1PCS", hpp: 3000, unitPacking: 1},
        {sku: "PNST-1BOX", nama: "PINSET STAINLESS 1 BOX", hpp: 25500, unitPacking: 1},
        {sku: "SSMP-1HNGR", nama: "SILET SUPERMAX 1 HANGER 40 KOTAK", hpp: 126500, unitPacking: 1},
        {sku: "SSMP-1/2HNGR", nama: "SILET SUPERMAX 1/2 HANGER 20 KOTAK", hpp: 63500, unitPacking: 1},
        {sku: "SSMP-1/4HNGR", nama: "SILET SUPERMAX 1/4 HANGER 10 KOTAK", hpp: 32000, unitPacking: 1},
        {sku: "LB90YCLR-1P", nama: "LAKBAN BENING 45MM 90Y 1 PCS", hpp: 5500, unitPacking: 1},
        {sku: "LB90YCLR-1S", nama: "LAKBAN BENING 45MM 90Y 1 SLOP", hpp: 32000, unitPacking: 1},
        {sku: "LB90YCKLT-1P", nama: "LAKBAN COKLAT 45MM 90Y 1 PCS", hpp: 5500, unitPacking: 1},
        {sku: "LB90YCKLT-1S", nama: "LAKBAN COKLAT 45MM 90Y 1 SLOP", hpp: 32000, unitPacking: 1},
        {sku: "LB200YCLR-1P", nama: "LAKBAN BENING 200Y 1 PCS", hpp: 11000, unitPacking: 1},
        {sku: "LB200YCLR-1S", nama: "LAKBAN BENING 200Y 1 SLOP", hpp: 66000, unitPacking: 1},
        {sku: "LB200YCKLT-1P", nama: "LAKBAN COKLAT 200Y 1 PCS", hpp: 11000, unitPacking: 1},
        {sku: "LB200YCKLT-1S", nama: "LAKBAN COKLAT 200Y 1 SLOP", hpp: 66000, unitPacking: 1},
        {sku: "LT78100300-1P", nama: "LABEL THERMAL 78X100 ISI 300", hpp: 19500, unitPacking: 1},
        {sku: "KOKAL", nama: "KOK AIRLANGGA 1 SLOP", hpp: 20000, unitPacking: 1},
        {sku: "GKUKU-1BOX", nama: "SAFARI GUNTING KUKU", hpp: 41000, unitPacking: 1},
];















